//! Client SDK for the [Overpay](https://overpay.com) marketplace API.
//!
//! The API is described by `openapi/v1.yaml` in the Overpay repository; this
//! crate carries a copy (`spec/`) together with the contract fixtures the
//! marketplace's own tests pin, and its tests check the SDK against both.
//!
//! - [`Client`] — one marketplace. Resources hang off it:
//!   [`Client::listings`], [`Client::orders`], [`Client::credits`],
//!   [`Client::spend_authorizations`], [`Client::account`],
//!   [`Client::buyer`], [`Client::oauth`].
//! - [`Auth`] — per request: none, an API token, or a NIP-98 signature
//!   ([`Nip98Signer`]), signed per attempt over the final URL.
//! - [`Response`] — the JSON exactly as sent, with a typed view on demand
//!   ([`Response::parse`] into the [`models`]).
//! - [`Error`] — API errors carry the machine-readable [`ErrorCode`].
//! - Safe retries: GETs, and order creation with an automatic
//!   `Idempotency-Key` ([`RetryPolicy`]).
//! - [`flows`] — place-and-pay with credits, waiting for (and streaming) an
//!   order's output, offloaded deliverables, spend sessions, provider-tool
//!   discovery, pagination, the OAuth PKCE login.
//!
//! ```no_run
//! # async fn demo() -> Result<(), Box<dyn std::error::Error>> {
//! use overpay_sdk::{flows::OrderWaiter, Auth, Client, CreateOrder};
//!
//! let client = Client::new("https://overpay.example")?;
//! let auth = Auth::Bearer("api-token");
//! let order = CreateOrder::new("listing-id")
//!     .buyer_note(r#"{"prompt":"hi"}"#)
//!     .client_session_id("conversation-label");
//! let paid = client.create_paid_order(&order, 50, auth).await?;
//! let done = OrderWaiter::new(&client, &paid.order_id, auth).wait().await?;
//! println!("{}", done.snapshot["data"]["delivered_content"]);
//! # Ok(()) }
//! ```

mod auth;
mod client;
mod delivery;
mod enums;
mod error;
pub mod flows;
// Generated by overpay-sdk-codegen; its output is canonical, so rustfmt
// leaves it alone (the `generated_is_fresh` test compares it byte for byte).
#[rustfmt::skip]
mod generated;
pub mod models;
mod operations;
mod pkce;
mod resources;
mod response;
#[cfg(feature = "testing")]
pub mod testing;

pub use auth::{Auth, InvalidKey, Nip98Signer, SecretKey, SIGNATURE_HEADER};
pub use client::{
    host_key, new_idempotency_key, Body, Client, ClientBuilder, Request, RetryPolicy,
    IDEMPOTENCY_KEY_HEADER, IDEMPOTENT_REPLAYED_HEADER,
};
pub use delivery::DeliveredContent;
pub use error::{describe_body, ApiError, Error};
pub use generated::{
    CreditTransactionType, ErrorCode, FulfillmentStatus, PaymentOutcomeStatus, PaymentStatus,
    PricingMode, RedemptionStatus, RefundStatus, RejectionReason, SpendAuthorizationStatus,
    OPERATIONS,
};
pub use operations::{Audience, Operation};
pub use pkce::Pkce;
pub use resources::{
    AccountApi, BuyerApi, CreateOrder, CreateSpendAuthorization, CreditsApi, GetOrder,
    ListingQuery, ListingsApi, OAuthApi, OrderQuery, OrdersApi, SellersApi, SpendAuthorizationsApi,
    TransactionQuery,
};
pub use response::{FromBody, RawResponse, Response};
