//! Renders `overpay-sdk/src/generated.rs` from the OpenAPI document.
//!
//! Only the parts of the spec that drift are generated: every string enum
//! a client branches on (error codes, order statuses, …) and the table of
//! operations. Models and request plumbing are hand-written in the SDK and
//! checked against the spec by its tests.
//!
//! `cargo run -p overpay-sdk-codegen` rewrites the file; the SDK's
//! `generated_is_fresh` test fails when it is stale.

use std::fmt::Write;

use serde_json::Value;

/// (Rust type name, JSON pointer to a schema with an `enum`, doc comment).
pub const ENUMS: &[(&str, &str, &str)] = &[
    (
        "ErrorCode",
        "/components/schemas/ErrorCode",
        "Machine-readable `code` on an API error. New codes may appear; unknown ones arrive as `Other`.",
    ),
    ("PaymentStatus", "/components/schemas/PaymentStatus", "An order's `payment_status`."),
    (
        "FulfillmentStatus",
        "/components/schemas/FulfillmentStatus",
        "An order's `fulfillment_status`. `Delivered`, `Failed`, `Cancelled` and `Rejected` are terminal.",
    ),
    (
        "RejectionReason",
        "/components/schemas/RejectionReason",
        "Why a seller rejected a paid order (`rejection.reason_code`).",
    ),
    (
        "PaymentOutcomeStatus",
        "/components/schemas/PaymentOutcome/properties/status",
        "How paying for a new order with `pay: merchant_credits` went (`payment.status`).",
    ),
    (
        "RedemptionStatus",
        "/components/schemas/Redemption/properties/status",
        "How redeeming merchant credits against an order went.",
    ),
    (
        "SpendAuthorizationStatus",
        "/components/schemas/SpendAuthorization/properties/status",
        "A spend authorization's lifecycle state.",
    ),
    (
        "PricingMode",
        "/components/schemas/Listing/properties/pricing_mode",
        "`Fixed`: the price is the price. `Metered`: the price is only the default authorization.",
    ),
    (
        "RefundStatus",
        "/components/schemas/Order/properties/refund_status",
        "How much of an order's payment came back to the buyer.",
    ),
    (
        "CreditTransactionType",
        "/components/schemas/MerchantCreditTransaction/properties/type",
        "The direction of a credit-ledger movement.",
    ),
];

const HTTP_METHODS: &[&str] = &["get", "put", "post", "delete", "patch"];

/// The full text of `generated.rs` for `spec`.
///
/// # Panics
/// If the spec lacks one of the schemas in [`ENUMS`], or an operation lacks
/// an `operationId`.
#[must_use]
pub fn render(spec: &Value) -> String {
    let mut out = String::from(
        "// @generated by overpay-sdk-codegen from spec/overpay-v1.json. Do not edit.\n\
         // Regenerate: cargo run -p overpay-sdk-codegen\n\n\
         use crate::enums::string_enum;\n\
         use crate::operations::{Audience, Operation};\n",
    );

    for (name, pointer, doc) in ENUMS {
        let values = spec
            .pointer(&format!("{pointer}/enum"))
            .and_then(Value::as_array)
            .unwrap_or_else(|| panic!("{pointer} has no enum"));
        writeln!(out, "\nstring_enum! {{\n    /// {doc}\n    {name} {{").unwrap();
        for v in values {
            let v = v.as_str().expect("enum values are strings");
            writeln!(out, "        {} = \"{v}\",", camel(v)).unwrap();
        }
        out.push_str("    }\n}\n");
    }

    out.push_str(
        "\n/// Every operation in the spec, by path.\npub const OPERATIONS: &[Operation] = &[\n",
    );
    // Sorted explicitly: serde_json's map order depends on whether some
    // crate in the build enables `preserve_order`, and the output must not.
    let mut paths: Vec<(&String, &Value)> =
        spec["paths"].as_object().expect("paths").iter().collect();
    paths.sort_by(|a, b| a.0.cmp(b.0));
    for (path, item) in paths {
        for method in HTTP_METHODS {
            let Some(op) = item.get(*method) else {
                continue;
            };
            let id = op["operationId"]
                .as_str()
                .unwrap_or_else(|| panic!("{method} {path} has no operationId"));
            let audience = match op.get("x-overpay-audience").and_then(Value::as_str) {
                Some("seller") => "Seller",
                Some("gateway") => "Gateway",
                Some(other) => panic!("unknown x-overpay-audience {other}"),
                None if tagged(op, "Meta") => "Meta",
                None => "Buyer",
            };
            writeln!(
                out,
                "    Operation {{ id: \"{id}\", method: \"{}\", path: \"{path}\", audience: Audience::{audience} }},",
                method.to_uppercase()
            )
            .unwrap();
        }
    }
    out.push_str("];\n");
    out
}

fn tagged(op: &Value, tag: &str) -> bool {
    op.get("tags")
        .and_then(Value::as_array)
        .is_some_and(|tags| tags.iter().any(|t| t == tag))
}

/// `authorization_too_low` → `AuthorizationTooLow`.
fn camel(value: &str) -> String {
    value
        .split(|c: char| !c.is_ascii_alphanumeric())
        .filter(|p| !p.is_empty())
        .map(|p| {
            let mut chars = p.chars();
            let first = chars.next().expect("non-empty").to_ascii_uppercase();
            std::iter::once(first).chain(chars).collect::<String>()
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn camel_cases_snake_values() {
        assert_eq!(camel("authorization_too_low"), "AuthorizationTooLow");
        assert_eq!(camel("paid"), "Paid");
    }
}
