#!/usr/bin/env bash
# Build owallet-web (owallet/crates/owallet-web) for the page: a release
# wasm32 build, then wasm-bindgen --target web into src/owallet-web/
# (generated, gitignored), which src/owallet.ts loads in the core worker.
#
#   bun run build:owallet        (from packages/web-tui)
#
# Needs: rustup target wasm32-unknown-unknown, clang + llvm-ar (secp256k1 and
# SQLite are C, cross-compiled to wasm32 — owallet/.cargo/config.toml points
# cargo at them), and wasm-bindgen-cli at exactly the wasm-bindgen version in
# owallet-web's Cargo.lock. Idempotent: cargo and wasm-bindgen only redo work
# when something changed.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
crate="$(cd "$here/../../owallet/crates/owallet-web" && pwd)"
out="$here/src/owallet-web"

die() {
  echo "build-owallet-web: $*" >&2
  exit 1
}

command -v cargo >/dev/null || die "cargo not found (install Rust: https://rustup.rs)"
if command -v rustup >/dev/null && ! rustup target list --installed | grep -qx wasm32-unknown-unknown; then
  die "the wasm32 target is missing: rustup target add wasm32-unknown-unknown"
fi
command -v "${CC_wasm32_unknown_unknown:-clang}" >/dev/null || die "clang not found (C deps are cross-compiled to wasm32 with it)"
command -v "${AR_wasm32_unknown_unknown:-llvm-ar}" >/dev/null || die "llvm-ar not found (install llvm)"

want="$(grep -A1 '^name = "wasm-bindgen"$' "$crate/Cargo.lock" | sed -n 's/^version = "\(.*\)"$/\1/p')"
[ -n "$want" ] || die "could not read the wasm-bindgen version from $crate/Cargo.lock"
bindgen="${WASM_BINDGEN:-wasm-bindgen}"
# `cargo install` puts it in ~/.cargo/bin, which is not always on PATH.
if ! command -v "$bindgen" >/dev/null && [ -x "${CARGO_HOME:-$HOME/.cargo}/bin/wasm-bindgen" ]; then
  bindgen="${CARGO_HOME:-$HOME/.cargo}/bin/wasm-bindgen"
fi
command -v "$bindgen" >/dev/null ||
  die "wasm-bindgen not found — cargo install wasm-bindgen-cli --version $want --locked"
have="$("$bindgen" --version | awk '{print $2}')"
[ "$have" = "$want" ] ||
  die "wasm-bindgen-cli is $have but Cargo.lock has wasm-bindgen $want — cargo install wasm-bindgen-cli --version $want --locked --force"

# The C toolchain for wasm32 (also in owallet/.cargo/config.toml; exported
# here too so an overriding CARGO_HOME config can't lose it).
export CC_wasm32_unknown_unknown="${CC_wasm32_unknown_unknown:-clang}"
export AR_wasm32_unknown_unknown="${AR_wasm32_unknown_unknown:-llvm-ar}"

echo "build-owallet-web: cargo build (wasm32, release)…" >&2
(cd "$crate" && cargo build --target wasm32-unknown-unknown --release --locked)

wasm="${CARGO_TARGET_DIR:-$crate/target}/wasm32-unknown-unknown/release/owallet_web.wasm"
[ -f "$wasm" ] || die "build produced no $wasm"

mkdir -p "$out"
if [ "$out/owallet_web_bg.wasm" -nt "$wasm" ] && [ -f "$out/owallet_web.js" ]; then
  echo "build-owallet-web: $out is up to date" >&2
else
  "$bindgen" --target web --out-dir "$out" "$wasm"
fi
# Generated output: keep it out of git without touching any other ignore file.
printf '# generated by scripts/build-owallet-web.sh\n*\n' >"$out/.gitignore"
echo "build-owallet-web: $(du -h "$out/owallet_web_bg.wasm" | cut -f1) wasm in $out" >&2
