// @generated by overpay-sdk-codegen from spec/overpay-v1.json. Do not edit.
// Regenerate: cargo run -p overpay-sdk-codegen

use crate::enums::string_enum;
use crate::operations::{Audience, Operation};

string_enum! {
    /// Machine-readable `code` on an API error. New codes may appear; unknown ones arrive as `Other`.
    ErrorCode {
        Unauthorized = "unauthorized",
        TokenRequired = "token_required",
        Nip98Invalid = "nip98_invalid",
        Nip98AddressMismatch = "nip98_address_mismatch",
        Forbidden = "forbidden",
        NotFound = "not_found",
        ValidationFailed = "validation_failed",
        InvalidParameter = "invalid_parameter",
        InvalidCursor = "invalid_cursor",
        InvalidStatusFilter = "invalid_status_filter",
        InvalidAmount = "invalid_amount",
        PayerAddressRequired = "payer_address_required",
        Conflict = "conflict",
        ListingUnavailable = "listing_unavailable",
        SellerCryptoMissing = "seller_crypto_missing",
        UnknownVariant = "unknown_variant",
        InvalidClientSessionId = "invalid_client_session_id",
        DuplicateSettlement = "duplicate_settlement",
        InvalidAuthorization = "invalid_authorization",
        ConflictingAuthorization = "conflicting_authorization",
        AuthorizationRequiresCredits = "authorization_requires_credits",
        AuthorizationNotSupported = "authorization_not_supported",
        AuthorizationOutOfBounds = "authorization_out_of_bounds",
        AuthorizationClosed = "authorization_closed",
        AuthorizationListingMismatch = "authorization_listing_mismatch",
        AuthorizationExhausted = "authorization_exhausted",
        InsufficientCredits = "insufficient_credits",
        NoCredits = "no_credits",
        OrderNotPayable = "order_not_payable",
        RedemptionFailed = "redemption_failed",
        IdempotencyKeyInvalid = "idempotency_key_invalid",
        IdempotencyKeyReused = "idempotency_key_reused",
        IdempotencyRequestInProgress = "idempotency_request_in_progress",
        UpstreamError = "upstream_error",
        UpstreamUnavailable = "upstream_unavailable",
    }
}

string_enum! {
    /// An order's `payment_status`.
    PaymentStatus {
        AwaitingQuote = "awaiting_quote",
        Quoted = "quoted",
        Pending = "pending",
        Paid = "paid",
        Expired = "expired",
        Cancelled = "cancelled",
    }
}

string_enum! {
    /// An order's `fulfillment_status`. `Delivered`, `Failed`, `Cancelled` and `Rejected` are terminal.
    FulfillmentStatus {
        Pending = "pending",
        AwaitingSeller = "awaiting_seller",
        Submitting = "submitting",
        Processing = "processing",
        Placed = "placed",
        Shipping = "shipping",
        Delivered = "delivered",
        Failed = "failed",
        Cancelled = "cancelled",
        Rejected = "rejected",
    }
}

string_enum! {
    /// Why a seller rejected a paid order (`rejection.reason_code`).
    RejectionReason {
        AuthorizationTooLow = "authorization_too_low",
        UnsupportedInput = "unsupported_input",
        UpstreamUnavailable = "upstream_unavailable",
    }
}

string_enum! {
    /// How paying for a new order with `pay: merchant_credits` went (`payment.status`).
    PaymentOutcomeStatus {
        FullyPaid = "fully_paid",
        Partial = "partial",
        AlreadyPaid = "already_paid",
        Failed = "failed",
    }
}

string_enum! {
    /// How redeeming merchant credits against an order went.
    RedemptionStatus {
        FullyPaid = "fully_paid",
        Partial = "partial",
        AlreadyPaid = "already_paid",
    }
}

string_enum! {
    /// A spend authorization's lifecycle state.
    SpendAuthorizationStatus {
        Open = "open",
        Closed = "closed",
        Expired = "expired",
    }
}

string_enum! {
    /// `Fixed`: the price is the price. `Metered`: the price is only the default authorization.
    PricingMode {
        Fixed = "fixed",
        Metered = "metered",
    }
}

string_enum! {
    /// How much of an order's payment came back to the buyer.
    RefundStatus {
        None = "none",
        Partial = "partial",
        Refunded = "refunded",
    }
}

string_enum! {
    /// The direction of a credit-ledger movement.
    CreditTransactionType {
        Load = "load",
        Spend = "spend",
        Refund = "refund",
    }
}

/// Every operation in the spec, by path.
pub const OPERATIONS: &[Operation] = &[
    Operation { id: "getOAuthMetadata", method: "GET", path: "/.well-known/oauth-authorization-server", audience: Audience::Buyer },
    Operation { id: "getApiIndex", method: "GET", path: "/api/v1", audience: Audience::Meta },
    Operation { id: "getAccount", method: "GET", path: "/api/v1/account", audience: Audience::Buyer },
    Operation { id: "registerBuyer", method: "POST", path: "/api/v1/buyer/register", audience: Audience::Buyer },
    Operation { id: "createWebSession", method: "POST", path: "/api/v1/buyer/web_session", audience: Audience::Buyer },
    Operation { id: "getOpenApiDocument", method: "GET", path: "/api/v1/docs", audience: Audience::Meta },
    Operation { id: "getApiDocsUi", method: "GET", path: "/api/v1/docs/ui", audience: Audience::Meta },
    Operation { id: "listListings", method: "GET", path: "/api/v1/listings", audience: Audience::Buyer },
    Operation { id: "getListing", method: "GET", path: "/api/v1/listings/{id}", audience: Audience::Buyer },
    Operation { id: "listMerchantCredits", method: "GET", path: "/api/v1/merchant_credits", audience: Audience::Buyer },
    Operation { id: "loadCoreCredits", method: "POST", path: "/api/v1/merchant_credits/load", audience: Audience::Buyer },
    Operation { id: "listMerchantCreditTransactions", method: "GET", path: "/api/v1/merchant_credits/transactions", audience: Audience::Buyer },
    Operation { id: "getMerchantCreditBalance", method: "GET", path: "/api/v1/merchant_credits/{seller_slug}", audience: Audience::Buyer },
    Operation { id: "purchaseMerchantCredits", method: "POST", path: "/api/v1/merchant_credits/{seller_slug}/purchase", audience: Audience::Buyer },
    Operation { id: "redeemMerchantCredits", method: "POST", path: "/api/v1/merchant_credits/{seller_slug}/redeem", audience: Audience::Buyer },
    Operation { id: "listOrders", method: "GET", path: "/api/v1/orders", audience: Audience::Buyer },
    Operation { id: "createOrder", method: "POST", path: "/api/v1/orders", audience: Audience::Buyer },
    Operation { id: "createX402Order", method: "POST", path: "/api/v1/orders/x402", audience: Audience::Gateway },
    Operation { id: "getOrder", method: "GET", path: "/api/v1/orders/{id}", audience: Audience::Buyer },
    Operation { id: "sellerListListings", method: "GET", path: "/api/v1/seller/listings", audience: Audience::Seller },
    Operation { id: "sellerCreateListing", method: "POST", path: "/api/v1/seller/listings", audience: Audience::Seller },
    Operation { id: "sellerGetListing", method: "GET", path: "/api/v1/seller/listings/{id}", audience: Audience::Seller },
    Operation { id: "sellerArchiveListing", method: "DELETE", path: "/api/v1/seller/listings/{id}", audience: Audience::Seller },
    Operation { id: "sellerUpdateListing", method: "PATCH", path: "/api/v1/seller/listings/{id}", audience: Audience::Seller },
    Operation { id: "sellerListLog", method: "GET", path: "/api/v1/seller/log", audience: Audience::Seller },
    Operation { id: "sellerListMerchantCredits", method: "GET", path: "/api/v1/seller/merchant_credits", audience: Audience::Seller },
    Operation { id: "sellerMintMerchantCredits", method: "POST", path: "/api/v1/seller/merchant_credits/mint", audience: Audience::Seller },
    Operation { id: "sellerUpsertMerchantCreditPolicy", method: "POST", path: "/api/v1/seller/merchant_credits/policies", audience: Audience::Seller },
    Operation { id: "sellerMerchantCreditSummary", method: "GET", path: "/api/v1/seller/merchant_credits/summary", audience: Audience::Seller },
    Operation { id: "sellerListOrders", method: "GET", path: "/api/v1/seller/orders", audience: Audience::Seller },
    Operation { id: "sellerGetOrder", method: "GET", path: "/api/v1/seller/orders/{id}", audience: Audience::Seller },
    Operation { id: "sellerCancelOrder", method: "PATCH", path: "/api/v1/seller/orders/{id}/cancel", audience: Audience::Seller },
    Operation { id: "sellerDeliverOrder", method: "PATCH", path: "/api/v1/seller/orders/{id}/deliver", audience: Audience::Seller },
    Operation { id: "sellerFailOrder", method: "PATCH", path: "/api/v1/seller/orders/{id}/fail", audience: Audience::Seller },
    Operation { id: "sellerGetOrderLog", method: "GET", path: "/api/v1/seller/orders/{id}/log", audience: Audience::Seller },
    Operation { id: "sellerAppendOrderLog", method: "POST", path: "/api/v1/seller/orders/{id}/log", audience: Audience::Seller },
    Operation { id: "sellerShipOrder", method: "PATCH", path: "/api/v1/seller/orders/{id}/ship", audience: Audience::Seller },
    Operation { id: "sellerReconcileOrganization", method: "PATCH", path: "/api/v1/seller/organization", audience: Audience::Seller },
    Operation { id: "sellerGetProfile", method: "GET", path: "/api/v1/seller/profile", audience: Audience::Seller },
    Operation { id: "sellerUpdateProfile", method: "PATCH", path: "/api/v1/seller/profile", audience: Audience::Seller },
    Operation { id: "registerSeller", method: "POST", path: "/api/v1/seller/register", audience: Audience::Seller },
    Operation { id: "getSeller", method: "GET", path: "/api/v1/sellers/{slug}", audience: Audience::Buyer },
    Operation { id: "createSpendAuthorization", method: "POST", path: "/api/v1/spend_authorizations", audience: Audience::Buyer },
    Operation { id: "getSpendAuthorization", method: "GET", path: "/api/v1/spend_authorizations/{id}", audience: Audience::Buyer },
    Operation { id: "closeSpendAuthorization", method: "POST", path: "/api/v1/spend_authorizations/{id}/close", audience: Audience::Buyer },
    Operation { id: "authorizeOAuth", method: "GET", path: "/oauth/authorize", audience: Audience::Buyer },
    Operation { id: "approveOAuth", method: "POST", path: "/oauth/authorize", audience: Audience::Buyer },
    Operation { id: "registerOAuthClient", method: "POST", path: "/oauth/clients", audience: Audience::Buyer },
    Operation { id: "exchangeOAuthToken", method: "POST", path: "/oauth/token", audience: Audience::Buyer },
];
