//! Byte-compatibility test: the Rust port must open and decrypt a wallet DB
//! produced by the Python `wallet_mcp.db` implementation.
//!
//! The fixture `fixtures/python_v0_1_0.db` is generated by
//! `fixtures/generate_python_v0_1_0.py` (see that file for the wire-format
//! details it reproduces). Regenerate after any schema change and commit
//! the new bytes.

use std::path::PathBuf;

use owallet_db::Database;
use tempfile::TempDir;

const PASSWORD: &str = "fixture-pw";
const NPUB: &str = "npub1fixturefixturefixture";
const MNEMONIC: &str = "abandon abandon abandon abandon abandon abandon \
     abandon abandon abandon abandon abandon about";

fn fixture_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join("python_v0_1_0.db")
}

/// Copy the read-only fixture into a tempdir so the test doesn't mutate it
/// (sqlite WAL/journal mode creates sidecar files on open).
fn copy_fixture() -> (TempDir, PathBuf) {
    let tmp = TempDir::new().expect("tempdir");
    let dst = tmp.path().join("python_v0_1_0.db");
    std::fs::copy(fixture_path(), &dst).expect("copy fixture");
    (tmp, dst)
}

#[test]
fn rust_unlocks_python_db_with_correct_password() {
    let (_tmp, path) = copy_fixture();
    let mut db = Database::open(&path).expect("open");
    assert!(db.unlock(PASSWORD).unwrap(), "expected unlock to succeed");
    assert!(db.is_unlocked());
}

#[test]
fn rust_rejects_python_db_with_wrong_password() {
    let (_tmp, path) = copy_fixture();
    let mut db = Database::open(&path).expect("open");
    assert!(!db.unlock("wrong").unwrap());
    assert!(!db.is_unlocked());
}

#[test]
fn rust_decrypts_seed_from_python_db() {
    let (_tmp, path) = copy_fixture();
    let mut db = Database::open(&path).expect("open");
    db.unlock(PASSWORD).unwrap();
    let seed = db.read_seed(NPUB).expect("read seed").expect("seed exists");
    assert_eq!(seed, MNEMONIC);
}

#[test]
fn rust_lists_wallet_metadata_from_python_db() {
    let (_tmp, path) = copy_fixture();
    let db = Database::open(&path).expect("open");
    // Listing wallets does not require unlock — metadata is plaintext.
    let wallets = db.list_wallets().unwrap();
    assert_eq!(wallets.len(), 1);
    let w = &wallets[0];
    assert_eq!(w.npub, NPUB);
    assert_eq!(
        w.address.as_deref(),
        Some("0x1234567890abcdef1234567890abcdef12345678")
    );
}

/// After unlocking the Python DB, the Rust port can write a new encrypted
/// wallet alongside the existing one, and the existing one still decrypts
/// (confirms we're not corrupting the key material on writes).
#[test]
fn rust_writes_next_to_python_wallet_without_breaking_it() {
    let (_tmp, path) = copy_fixture();
    let mut db = Database::open(&path).expect("open");
    db.unlock(PASSWORD).unwrap();

    let new_npub = "npub1rust";
    let new_seed = "0xdeadbeef";
    db.write_wallet(new_npub, new_seed, None).unwrap();

    assert_eq!(
        db.read_seed(NPUB).unwrap().as_deref(),
        Some(MNEMONIC),
        "Python wallet still readable after Rust write"
    );
    assert_eq!(
        db.read_seed(new_npub).unwrap().as_deref(),
        Some(new_seed),
        "Rust-written wallet readable"
    );
}
